PROFILE = {
    "dotfiles_root": "$HOME/Dev-Work/dotfiles",
    "env": {
        "EDITOR": "nvim",
        "BUN_INSTALL": "$HOME/.bun",
    },
    "paths": [
        "$HOME/.amp/bin",
        "/home/linuxbrew/.linuxbrew/bin",
        "/home/linuxbrew/.linuxbrew/sbin",
        "$HOME/.local/share/pnpm",
        "$HOME/.cargo/bin",
        "$HOME/.local/bin",
        "/usr/lib/cache/bin/",
    ],
    "fastfetch": {
        "default": "fastfetch/config.jsonc",
        "caelestia": "fastfetch/config-v2.jsonc",
    },
    "fnm_path": "$HOME/.local/share/fnm",
    "aliases": {
        "c": "clear",
        "ls": "eza --icons --group-directories-first -1",
        "ll": "eza -l --icons --group-directories-first",
        "la": "eza -a --icons --group-directories-first",
        "lla": "eza -la --icons --group-directories-first",
        "lt": "eza -a --tree --level=1 --icons=always",
        "fastfetch": "ff",
        "nf": "ff",
        "pf": "ff",
        "shutdown": "systemctl poweroff",
        "wifi": "nmtui",
        "ncode": "nvim",
        "update-grub": "sudo grub-mkconfig -o /boot/grub/grub.cfg",
    },
    "fish": {
        "abbrs": {
            # Misc
            "lg": "lazygit",
            # Yarn
            "yd": "yarn dev",
            "yb": "yarn build",
            "yf": "yarn format",
            "yst": "yarn start",
            "yln": "yarn lint",
            # Git - core
            "g": "git",
            "ga": "git add",
            "gaa": "git add --all",
            "gapa": "git add --patch",
            "gau": "git add --update",
            "gb": "git branch",
            "gba": "git branch -a",
            "gbd": "git branch -d",
            "gbD": "git branch -D",
            "gbl": "git blame -b -w",
            "gbnm": "git branch --no-merged",
            "gbr": "git branch --remote",
            "gbs": "git bisect",
            "gbsb": "git bisect bad",
            "gbsg": "git bisect good",
            "gbsr": "git bisect reset",
            "gbss": "git bisect start",
            "gc": "git commit -v",
            "gc!": "git commit -v --amend",
            "gcn!": "git commit -v --no-edit --amend",
            "gcam": "git commit -a -m",
            "gcas": "git commit -a -s",
            "gcasm": "git commit -a -s -m",
            "gcb": "git checkout -b",
            "gcd": "git checkout develop",
            "gcf": "git config --list",
            "gcl": "git clone --recurse-submodules",
            "gclean": "git clean -id",
            "gcm": "git checkout main",
            "gcmsg": "git commit -m",
            "gco": "git checkout",
            "gcor": "git checkout --recurse-submodules",
            "gcount": "git shortlog -sn",
            "gcp": "git cherry-pick",
            "gcpa": "git cherry-pick --abort",
            "gcpc": "git cherry-pick --continue",
            "gcs": "git commit -S",
            "gd": "git diff",
            "gdca": "git diff --cached",
            "gdcw": "git diff --cached --word-diff",
            "gds": "git diff --staged",
            "gdt": "git diff-tree --no-commit-id --name-only -r",
            "gdup": "git diff @{upstream}",
            "gdw": "git diff --word-diff",
            "gf": "git fetch",
            "gfa": "git fetch --all --prune",
            "gfo": "git fetch origin",
            "gg": "git gui citool",
            "gga": "git gui citool --amend",
            "ghh": "git help",
            "gignore": "git update-index --assume-unchanged",
            "gignored": 'git ls-files -v | grep "^[[:lower:]]"',
            "gk": "gitk --all --branches",
            "gl": "git pull",
            "glg": "git log --stat",
            "glgg": "git log --graph",
            "glgga": "git log --graph --decorate --all",
            "glgm": "git log --graph --max-count=20",
            "glgp": "git log --stat -p",
            "glog": "git log --oneline --decorate --graph",
            "gloga": "git log --oneline --decorate --graph --all",
            "gm": "git merge",
            "gma": "git merge --abort",
            "gmt": "git mergetool --no-prompt",
            "gmtvim": "git mergetool --no-prompt --tool=vimdiff",
            "gp": "git push",
            "gpd": "git push --dry-run",
            "gpf": "git push --force",
            "gpf!": "git push --force-with-lease",
            "gpoat": "git push origin --all && git push origin --tags",
            "gpr": "git pull --rebase",
            "gpristine": "git reset --hard && git clean -dffx",
            "gpu": "git push upstream",
            "gpv": "git push -v",
            "gr": "git remote",
            "gra": "git remote add",
            "grb": "git rebase",
            "grba": "git rebase --abort",
            "grbc": "git rebase --continue",
            "grbd": "git rebase develop",
            "grbi": "git rebase -i",
            "grbm": "git rebase main",
            "grbo": "git rebase --onto",
            "grbs": "git rebase --skip",
            "grev": "git revert",
            "grh": "git reset",
            "grhh": "git reset --hard",
            "grm": "git rm",
            "grmc": "git rm --cached",
            "grmv": "git remote rename",
            "grrm": "git remote remove",
            "grs": "git restore",
            "grset": "git remote set-url",
            "grss": "git restore --source",
            "gru": "git reset --",
            "grup": "git remote update",
            "grv": "git remote -v",
            "gsb": "git status -sb",
            "gsh": "git show",
            "gsps": "git show --pretty=short --show-signature",
            "gss": "git status -s",
            "gst": "git status",
            "gsta": "git stash push",
            "gstaa": "git stash apply",
            "gstc": "git stash clear",
            "gstd": "git stash drop",
            "gstl": "git stash list",
            "gstp": "git stash pop",
            "gsts": "git stash show --text",
            "gsu": "git submodule update",
            "gsw": "git switch",
            "gswc": "git switch -c",
            "gtl": "git tag --sort=-v:refname",
            "gts": "git tag -s",
            "gtv": "git tag | sort -V",
            "gunignore": "git update-index --no-assume-unchanged",
            "gup": "git pull --rebase",
            "gupv": "git pull --rebase -v",
            "gupa": "git pull --rebase --autostash",
            "gupav": "git pull --rebase --autostash -v",
            "gwch": "git whatchanged -p --abbrev-commit --pretty=medium",
        },
        "greeting_lines": [],
        "prompt_event": "mark_prompt_start",
    },
}
